---
title: "p8105_hw3_fy2297"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
# some figure preferences in global options (copied from lecture)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
# Problem 1

```{r}
library(p8105.datasets)
data("instacart")
```


# Problem 2
```{r}
# load, tidy, and otherwise wrangle the data.
accel_df = read_csv("./datahw3/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    values_to = "activity_value"
  ) %>% 
  mutate(
    weekday_vs_weekend = case_when(
      day == "Saturday" | day == "Sunday" ~ "weekend",
      day != "Saturday" | day != "Sunday" ~ "weekday",
      TRUE                                ~ ""
    )
  )
# describe the resulting dataset


# create a table that shows total activity for each day
accel_df %>% 
  group_by(week, day) %>% 
  summarize(
    total_activity = sum(activity_value)
  ) %>%
  arrange(day) %>% 
  group_by(day) %>% 
  pivot_wider(
    names_from = day,
    values_from = total_activity
  ) %>% 
  knitr::kable(digit = 1)
# describe the trend in the table


# create a dataset for plotting
accel_plot_df = 

# make a plot that shows 24-hour activity time for each day
ggplot(accel_df, aes(x = activity, y = activity_value, color = day)) + geom_point() + geom_line()

```

# Problem 3
```{r}
# load and clean the data for future use
library(p8105.datasets)
data("ny_noaa")

noaa_df = 
  ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = '-') %>% 
  rename(
    tmax_frenheit = tmax,
    tmin_frenheit = tmin,
    prcp_mm = prcp,
    snow_mm = snow
  ) 
# find the most commonly observed value for snowfall
noaa_snow_count = 
  noaa_df %>% 
  group_by(snow_mm) %>% 
  summarize(
    n_obs_snow = n()
  ) %>% 
  arrange(-n_obs_snow)
```
The most commonly observed values for snowfall are 0mm, 25mm, 13mm, 51mm, and 76mm. Why???

```{r}
# make a two-panel plot showing the average max temp. in Jan and July in each station across years
jan_plot = 
 noaa_df %>% 
  filter(month == "01")%>% 
  group_by(year,month) %>% 
  mutate(
    tmax_frenheit = as.numeric(tmax_frenheit),
    year = as.numeric(year)
  )%>% 
  summarize(average_tmax = mean(tmax_frenheit, na.rm = TRUE)) %>% 
  ggplot(aes(x =year, y = average_tmax)) + geom_point() + geom_line() + labs(
    title = "max temperature in January in each station across years",
    x = "year",
    y = "avarage max temperature in January"
  )

july_plot = 
  noaa_df %>% 
  filter(month == "07")%>% 
  group_by(year,month) %>% 
  mutate(
    tmax_frenheit = as.numeric(tmax_frenheit),
    year = as.numeric(year)
  )%>% 
  summarize(average_tmax = mean(tmax_frenheit, na.rm = TRUE)) %>% 
  ggplot(aes(x =year, y = average_tmax)) + geom_point() + geom_line() + labs(
    title = "max temperature in July in each station across years",
    x = "year",
    y = "avarage max temperature in July"
  )
  
jan_plot+july_plot
```

```{r}
# make a two-panel plot showing 1. tmax vs tmin for the full dataset 2. distribution of snowfall values greater than 0 and less than 100 separately by year.
tmax_vs_tmin = 
  noaa_df %>% 
  ggplot(aes(x = tmax_frenheit, y = tmin_frenheit)) + geom_point() + geom_line()

tmax_vs_tmin

dist_snow = 
  noaa_df %>% 
  filter(snow_mm <= 100 & snow_mm >=0) %>% 
  ggplot(aes(x = snow_mm, fill = snowfall_value)) +
  geom_density()
dist_snow

```







